experimentName: value_accumulation
searchSpaceFile: search_space.json
trialCommand: python nni_experiment.py
trialCodeDirectory: .
trialConcurrency: 8
maxExperimentDuration: 2h
maxTrialNumber: 50
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: False