experimentName: compare_mechanisms
searchSpaceFile: params.json
trialCommand: python compare_mechanisms.py
trialCodeDirectory: ..
trialConcurrency: 8
maxExperimentDuration: 72h
maxTrialNumber: 1000
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: False
